# This sets up a system for testing chainlink against block re-orgs and ommers.
#
# The geth<n> nodes are arranged in a cooperating network. See the README.md and
# the instructions in `initialize-node-data.sh` for details.
#
# One geth node is run at 6 times the speed of the other. The chainlink node is
# connected to the slow one. Disconnect the fast one from the network to induce
# a block re-org on the chainlink node.
#
# The speeds are controlled by the `cpus` fields. Note that in order to invoke
# this composition, it's necessary to call `docker-compose` with the
# `--compatibility` option, because the `deploy` field containing the `cpus`
# field is only supposed to be invoked by docker swarm.
#
# If you modify this, make sure to make corresponding modifications to the
# `geth-config-*.toml` files. `geth` is bad about letting you know when it's
# getting inconsistent inputs, so be careful.

version: "3.1"

services:
  # Slow-mining geth node which chainlink connects to.
  geth1:
    image: geth
    restart: on-failure
    # --miner.threads must be positive, or geth won't mine!
    command: --mine
      --miner.threads 1
      --config /root/geth-config-1.toml
      --unlock "0x9ca9d2d5e04012c9ed24c0e513c9bfaa4a2dd77f"
      --password /run/secrets/node_password
      --nat extip:172.16.1.100 # Must match ipv4_address for this container
    volumes:
      - .:/root
    networks:
      gethnet:
        ipv4_address: 172.16.1.100
    secrets:
      - node_password
    deploy:
      resources:
        limits:
          # Make this node slow, so while it's disconnected from the fast node,
          # it'll construct a weaker blockchain.
          cpus: "0.5"

  # Fast-mining geth node which generates the block re-organization, when it's
  # reconnected to geth1.
  geth2:
    image: geth
    restart: on-failure
    # --miner.threads must be positive, or geth won't mine!
    command: --mine
      --miner.threads 1
      --config /root/geth-config-2.toml
      --unlock "0x9ca9d2d5e04012c9ed24c0e513c9bfaa4a2dd77f"
      --password /run/secrets/node_password
      --nat extip:172.16.1.101 # Must match ipv4_address for this container
    volumes:
      - .:/root
    networks:
      gethnet:
        ipv4_address: 172.16.1.101
    secrets:
      - node_password
    deploy:
      resources:
        limits:
          # Make this node fast, so when it's disconnected from the network
          # it'll construct a stronger blockchain.
          cpus: "3"

  # Chainlink node which is connected to the slow-mining geth node
  chainlink:
    image: smartcontract/chainlink
    command: local node -d -p /run/secrets/node_password -a /run/secrets/node_api
    restart: always
    volumes:
      - ../../tools/clroot/:/root/clroot
    environment:
      - LOG_LEVEL=debug
      - ETH_URL=ws://geth1:8546 # Gets ethereum information from slow geth node
      - ROOT=/root/clroot
      - ETH_CHAIN_ID=17
      - MIN_OUTGOING_CONFIRMATIONS=2
      - MINIMUM_CONTRACT_PAYMENT=1000000000000
      - CHAINLINK_DEV=true
    networks:
      gethnet:
        ipv4_address: 172.16.1.102
    depends_on:
      - geth1
    expose:
      - 6688
    secrets:
      - node_password
      - node_api
    deploy:
      resources:
        limits:
          cpus: "0.5"

networks:
  gethnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.1.0/24

secrets:
  node_password:
    file: ./secrets/password.txt
  node_api:
    file: ./secrets/apicredentials
