# This sets up a system for testing chainlink against block re-orgs and ommers.
#
# The geth<n> nodes are arranged in a cooperating network. See the README.md and
# the instructions in `initialize-node-data.sh` for details.
#
# One geth node is run at 6 times the speed of the other. The chainlink node is
# connected to the slow one. Disconnect the fast one from the network to induce
# a block re-org on the chainlink node.
#
# The speeds are controlled by the `cpus` fields. Note that in order to invoke
# this composition, it's necessary to call `docker-compose` with the
# `--compatibility` option, because the `deploy` field containing the `cpus`
# field is only supposed to be invoked by docker swarm.
#
# If you modify this, make sure to make corresponding modifications to the
# `geth-config-*.toml` files. `geth` is bad about letting you know when it's
# getting inconsistent inputs, so be careful.

version: "3.1"

services:
  # Static bootnode for other nodes to use to connect
  bootnode:
    image: bootnode
    restart: on-failure
    volumes:
      - .:/root
    networks:
      gethnet:
        ipv4_address: 172.16.1.103
    deploy:
      resources:
        limits:
          cpus: "0.5"

  # Slow-mining geth node which chainlink connects to.
  geth1:
    image: geth
    restart: on-failure
    command: --nousb
      --config /root/geth-config-1.toml
      --unlock "0x9ca9d2d5e04012c9ed24c0e513c9bfaa4a2dd77f"
      --password /run/secrets/node_password
      --nat extip:172.16.1.100 # Must match ipv4_address for this container
    volumes:
      - .:/root
    networks:
      gethnet:
        ipv4_address: 172.16.1.100
    secrets:
      - node_password

  chainlink_key_import:
    image: smartcontract/chainlink
    command: local import /root/clroot/keys/0x9CA9d2D5E04012C9Ed24C0e513C9bfAa4A2dD77f.json
    volumes:
      - ./chainlink_node/clroot_tmp/:/root/clroot
    environment:
      - ROOT=/root/clroot

  chainlink:
    image: smartcontract/chainlink
    command: local node -d -p /run/secrets/node_password -a /run/secrets/node_api_credentials
    restart: always
    volumes:
      - ../../tools/clroot/:/root/clroot
    environment:
      - LOG_LEVEL=debug
      - ETH_URL=ws://geth1:8546 # Gets ethereum information from slow geth node
      - ROOT=/root/clroot
      - ETH_CHAIN_ID=17
      - MIN_OUTGOING_CONFIRMATIONS=2
      - MINIMUM_CONTRACT_PAYMENT=1000000000000
      - CHAINLINK_DEV=true
    networks:
      gethnet:
        ipv4_address: 172.16.1.102
    depends_on:
      - chainlink_key_import
    expose:
      - 6688
    secrets:
      - node_password
      - node_api_credentials

networks:
  gethnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.1.0/24

secrets:
  node_password:
    file: ./chainlink_node/secrets/password.txt
  node_api_credentials:
    file: ./chainlink_node/secrets/apicredentials
