version: '3.1'

services:

  geth1:
    image: ethereum/client-go
    restart: on-failure
    # --miner.threads must be positive, or geth won't mine!
    command:
      --mine
      --miner.threads 1 
      --config /root/geth-config-1.toml
      --unlock "0x9ca9d2d5e04012c9ed24c0e513c9bfaa4a2dd77f"
      --password /run/secrets/node_password
      --nat extip:172.16.1.100 # Must match ipv4_address for this container
    volumes:
      - .:/root
    networks:
      gethnet:
        ipv4_address: 172.16.1.100
    ports:
      - 8456
    secrets:
      - node_password
    deploy:
      resources:
        limits:
          cpus: "0.5"

  geth2:
    image: ethereum/client-go
    restart: on-failure
    # --miner.threads must be positive, or geth won't mine!
    command:
      --mine
      --miner.threads 1
      --config /root/geth-config-2.toml
      --nat extip:172.16.1.101 # Must match ipv4_address for this container
    volumes:
      - .:/root
    networks:
      gethnet:
        ipv4_address: 172.16.1.101
    secrets:
      - node_password
    deploy:
      resources:
        limits:
          cpus: "3"
      
  chainlink:
    image: smartcontract/chainlink
    command:
      local node -d -p /run/secrets/node_password -a /run/secrets/node_api
    restart: always
    volumes:
      - ../../tools/clroot/:/root/clroot
    environment:
      - LOG_LEVEL=debug
      - ETH_URL=ws://geth1:8546
      - ROOT=/root/clroot
      - ETH_CHAIN_ID=17
      - MIN_OUTGOING_CONFIRMATIONS=2
      - MINIMUM_CONTRACT_PAYMENT=1000000000000
      - CHAINLINK_DEV=true
    networks:
      gethnet:
        ipv4_address: 172.16.1.102
    depends_on:
      - geth1
    ports:
      - 6688
    secrets:
      - node_password
      - node_api
    deploy:
      resources:
        limits:
          cpus: "0.5"

networks:
  gethnet:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.1.0/24

secrets:
  node_password:
    file: ./secrets/password.txt
  node_api:
    file: ./secrets/apicredentials
