version: '3.1'

services:

  db:
    image: postgres
    networks:
      devnet:
        ipv4_address: 172.16.1.100
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./tools/docker/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: explorer_dev

  devnet:
    image: smartcontract/devnet
    networks:
      devnet:
        ipv4_address: 172.16.1.101

  chainlink:
    image: smartcontract/chainlink
    command: local node -d -p /run/secrets/node_password -a /run/secrets/apicredentials
    restart: always
    volumes:
      - ./tools/clroot/:/root/clroot
    environment:
      - ETH_CHAIN_ID=34055
      - LOG_LEVEL=debug
      - ROOT=/root/clroot
      - ETH_URL=ws://172.16.1.101:8546
      - MIN_OUTGOING_CONFIRMATIONS=2
      - MINIMUM_CONTRACT_PAYMENT=1000000000000
      - RUST_BACKTRACE=1
      - CHAINLINK_DEV=true
      - EXPLORER_URL=ws://172.16.1.103:8080
      # Development only credentials, requires record in node table in tools/docker/docker-entrypoint-initdb.d/explorer_schema.sql
      - EXPLORER_ACCESS_KEY=u4HULe0pj5xPyuvv
      - EXPLORER_SECRET=YDxkVRTmcliehGZPw7f0L2Td3sz3LqutAQyy7sLCEIP6xcWzbO8zgfBWi4DXC6U6
      #
    networks:
      devnet:
        ipv4_address: 172.16.1.102
    ports:
      - 8131:6688
    depends_on:
      - devnet
    secrets:
      - node_password
      - apicredentials

  explorer:
    image: smartcontract/explorer
    restart: always
    networks:
      devnet:
        ipv4_address: 172.16.1.103
    ports:
      - 8132:8080
    depends_on:
      - db
    environment:
      TYPEORM_DATABASE: explorer_dev
      TYPEORM_USERNAME: postgres
      TYPEORM_HOST: 172.16.1.100
      TYPEORM_PORT: 5432

networks:
  devnet:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.1.0/24

secrets:
  node_password:
    file: ./tools/clroot/password.txt
  apicredentials:
    file: ./tools/clroot/apicredentials

volumes:
  db-data:
    driver: local
