name: Validate Solidity Artifacts
description: Checks whether Slither reports and UML diagrams were generated for all necessary files. If not, a warning is printed in job summary, but the job is not marked as failed.
inputs:
  slither_reports_path:
    description: Path to the Slither reports directory (without trailing slash)
    required: true
  uml_diagrams_path:
    description: Path to the UML diagrams directory  (without trailing slash)
    required: true
  validate_slither_reports:
    description: Whether Slither reports should be validated
    required: true
  validate_uml_diagrams:
    description: Whether UML diagrams should be validated
    required: true
  sol_files:
    description: Comma-separated list of Solidity files to check
    required: true
  # remove this when AurorNZ/paths-filter is fixed
  base_ref:
    description: Base reference for comparison (skip if your list doesn't contain deleted files)
    required: false

runs:
  using: composite
  steps:
  - name: Validate UML diagrams
    if: ${{ inputs.validate_uml_diagrams == 'true' }}
    shell: bash
    run: |
      echo "Validating UML diagrams"
      IFS=',' read -r -a modified_files <<< "${{ inputs.sol_files }}"
      missing_svgs=()
      for file in "${modified_files[@]}"; do
        if [ "${{ inputs.base_ref }}" != "" ]; then
          # TODO remove this check when AurorNZ/paths-filter is fixed
          status=$(git diff --name-status ${{ inputs.base_ref }} ${{ github.sha }} -- "$file"  | awk '{ print $1 }')
          if [ "$status" == "D" ]; then
            echo "File $file was deleted, skipping validation"
            continue
          fi
        fi
      
        svg_file="$(basename "${file%.sol}").svg"
        if [ ! -f "${{ inputs.uml_diagrams_path }}/$svg_file" ]; then
          echo "Error: UML diagram for $file not found"
          missing_svgs+=("$file")
        fi
      done
      
      if [ ${#missing_svgs[@]} -gt 0 ]; then
          echo "Error: Missing UML diagrams for files: ${missing_svgs[@]}"
          echo "# Warning!" >> $GITHUB_STEP_SUMMARY
          echo "## Reason: Missing UML diagrams for files:" >> $GITHUB_STEP_SUMMARY
          for file in "${missing_svgs[@]}"; do
            echo " $file" >> $GITHUB_STEP_SUMMARY
          done
          echo "## Action required: Please try to generate artifacts for them locally or using a different tool" >> $GITHUB_STEP_SUMMARY
      else 
          echo "All UML diagrams generated successfully"
      fi

  - name: Validate Slither reports
    if: ${{ inputs.validate_slither_reports == 'true' }}
    shell: bash
    run: |
      echo "Validating Slither reports"
      IFS=',' read -r -a modified_files <<< "${{ inputs.sol_files }}"
      missing_reports=()
      for file in "${modified_files[@]}"; do
        if [ "${{ inputs.base_ref }}" != "" ]; then
          # TODO remove this check when AurorNZ/paths-filter is fixed
          status=$(git diff --name-status ${{ inputs.base_ref }} ${{ github.sha }} -- "$file"  | awk '{ print $1 }')
          if [ "$status" == "D" ]; then
            echo "File $file was deleted, skipping validation"
            continue
          fi
        fi
      
        report_file="$(basename "${file%.sol}")-slither-report.md"            
        if [ ! -f "${{ inputs.slither_reports_path }}/$report_file" ]; then
          echo "Error: Slither report for $file not found"
          missing_reports+=("$file")
        fi
      done
      
      if [ ${#missing_reports[@]} -gt 0 ]; then
          echo "Error: Missing Slither reports for files: ${missing_reports[@]}"
          echo "# Warning!" >> $GITHUB_STEP_SUMMARY
          echo "## Reason: Missing Slither reports for files:" >> $GITHUB_STEP_SUMMARY
          for file in "${missing_reports[@]}"; do
            echo " $file" >> $GITHUB_STEP_SUMMARY
          done
          echo "## Action required: Please try to generate artifacts for them locally" >> $GITHUB_STEP_SUMMARY
      else 
         echo "All Slither reports generated successfully"
      fi      
