version: 2
jobs:
  unit-tests:
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}-{{checksum "client/yarn.lock" }}
      - run:
          name: Install Server Packages
          command: yarn install
      - run:
          name: Install Client Packages
          command: cd client && yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}-{{checksum "client/yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Run Server Tests
          command: yarn test
      - run:
          name: Run Client Tests
          command: cd client && yarn test

workflows:
  version: 2
  test:
    jobs:
      - unit-tests
