ChainID = '59902'
ChainType = 'optimismBedrock'
FinalityTagEnabled = true
MinIncomingConfirmations = 1
NoNewHeadsThreshold = '0'

[EVM.GasEstimator]
Mode = 'SuggestedPrice'
PriceMin = '0'
LimitDefault = 8000000

[EVM.GasEstimator.BlockHistory]
BlockHistorySize = 0

[EVM.NodePool]
SyncThreshold = 10

[EVM.OCR]
ContractConfirmations = 1
