ChainID = '80002'
FinalityDepth = 500
LogPollInterval = '1s'
MinIncomingConfirmations = 5
NoNewHeadsThreshold = '30s'
RPCBlockQueryDelay = 10
RPCDefaultBatchSize = 100

[Transactions]
MaxQueued = 5000

[GasEstimator]
Mode = 'Universal'
EIP1559DynamicFees = true
PriceMax = '600 gwei'
BumpMin = '20 gwei'
BumpThreshold = 5

[GasEstimator.BlockHistory]
BlockHistorySize = 24

[HeadTracker]
HistoryDepth = 2000

[NodePool]
SyncThreshold = 10
