name: Setup Slither
description: Installs Slither for contract analysis. Requires Python 3.6 or higher.
runs:
  using: composite
  steps:
    - name: Install Slither
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install slither-analyzer
