version: '3.1'

services:
  integration:
    volumes:
      - ../../integration:/chainlink/integration
      - ../ci/ethereum_test:/chainlink/tools/ci/ethereum_test
  node:
    entrypoint: '/bin/sh -c "while sleep 1000; do :; done"'
    build:
      context: ../../
      dockerfile: tools/docker/cldev.Dockerfile
    command: ''
    image: smartcontract/chainlink-dev
    volumes:
      - ../..:/chainlink
  operator-ui:
    container_name: operator-ui
    image: smartcontract/operator-ui
    build:
      context: ../../
      dockerfile: tools/docker/operatorui.Dockerfile
    entrypoint: /bin/sh -c 'yarn && yarn setup && yarn workspace @chainlink/operator-ui start'
    environment: 
      - CHAINLINK_PORT
    ports:
      - 3000:3000
      - 4000:4000
    volumes: 
      - ../..:/chainlink
    depends_on:
      - node
