version: '3.1'

services:
  node:
    environment:
      - ETH_CHAIN_ID=1337
    depends_on:
      - devnet
  devnet:
    build: ../gethnet
    container_name: geth
    image: smartcontract/gethnet
    secrets:
      - node_password
