version: '3.1'

services:
  integration:
    container_name: integration-tests
    image: smartcontract/integration
    build:
      context: ../../
      dockerfile: tools/docker/integration.Dockerfile
    volumes:
      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - node
      - echo-server
      - cypress-job-server
    environment:
      - GETH_MODE
      - CHAINLINK_DEV=TRUE # need this for service agreements subcommand
      - CHAINLINK_URL
      - ETH_HTTP_URL
      - ECHO_SERVER_URL
      - CLIENT_NODE_URL # used to send remote commands
      - CYPRESS_JOB_SERVER_PORT
      - CYPRESS_JOB_SERVER_HOST
      - CYPRESS_EXPLORER_URL
      - CYPRESS_CHAINLINK_URL=$CHAINLINK_URL
    networks:
      - explorer-external
      - node-external
      - ethereum-node
      - integration-internal
    secrets:
      - apicredentials

  echo-server:
    container_name: echo-server
    image: smartcontract/echo-server
    build:
      context: ../../
      dockerfile: tools/docker/echo-server.Dockerfile
    environment:
      - PORT=$ECHO_SERVER_PORT
    networks:
      - integration-internal

  cypress-job-server:
    container_name: cypress-job-server
    image: smartcontract/cypress-job-server
    build:
      context: ../../
      dockerfile: tools/docker/cypress-job-server.Dockerfile
    command: '{\"last\":\ \"3843.95\"}'
    ports:
      - '6692:6692'
    environment:
      - JOB_SERVER_PORT=$CYPRESS_JOB_SERVER_PORT
    networks:
      - integration-internal

  node:
    entrypoint: ''
    command: /bin/sh -c "chainlink node import /run/secrets/keystore && chainlink node start -d -p /run/secrets/node_password -a /run/secrets/apicredentials"
    environment:
      ALLOW_ORIGINS: http://localhost:3000,http://localhost:6688,http://integration:3000,http://integration:6688,http://node:3000,http://node:6688
    networks:
      - node-external
      - integration-internal # needed this for echo-server, and cypress-job-server
    secrets:
      - keystore

networks:
  node-external:
    driver: bridge
  integration-internal:
    driver: bridge

secrets:
  keystore:
    file: ../secrets/0x9CA9d2D5E04012C9Ed24C0e513C9bfAa4A2dD77f.json
