version: '3.5'

services:
  node:
    depends_on:
      - devnet
  node-2:
    depends_on:
      - devnet
  devnet:
    container_name: parity
    image: smartcontract/devnet@sha256:a5768cb8a6e4b2aecdbbae7e95ba00c2e3b9a252685f2a675f9fa0db8d30c45a
    user: root
    command: --config /devnet/miner.toml --db-path /devnet/database
    ports:
      - 8545:8545
      - 8546:8546
    volumes:
      - parity-db-data:/devnet/database
volumes:
  parity-db-data:
