name: Go Mod Validator
run-name: CI Core ${{ inputs.distinct_run_name && inputs.distinct_run_name || '' }}

on:
  push:
    branches:
      - RE-2785-test
  workflow_dispatch:
    inputs:
      github_token:
        description: "A unique identifier for this run, used when running from other repos"
        required: false
        type: string

jobs:
    go-mod-validation:
        runs-on: ubuntu-latest
        steps:
          - name: Check out the repository
            uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
          - name: Setup go
            uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
          - name: go-mod-validation
            uses: smartcontractkit/.github/apps/go-mod-validator@db33f91945f33817a18b387eeff023c3dffd1a70 # 0.0.0
