name: Go Mod Validator
run-name: CI Core ${{ inputs.distinct_run_name && inputs.distinct_run_name || '' }}

on:
  push:
    branches:
      - RE-2785-test
  workflow_dispatch:
    inputs:
      github_token:
        description: "A unique identifier for this run, used when running from other repos"
        required: false
        type: string

jobs:
    go-mod-validation:
        runs-on: ubuntu-latest
        steps:
          - name: go-mod-validation
            uses: smartcontractkit/.github/apps/go-mod-validator@798b8df97d93d03e0a56d7d23c99a4a0072df3da # 0.0.0
            with:
              github_action_ref: 798b8df97d93d03e0a56d7d23c99a4a0072df3da
