name: golangci-lint

on:
  push:
    branches:
      - staging
      - trying
      - rollup
  pull_request:
    branches-ignore:
      - 'release/**'
  schedule:
    - cron: '0 0 * * *'

jobs:
  changes:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.changes.outputs.src }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
      - uses: dorny/paths-filter@b2feaf19c27470162a626bd6fa8438ae5b263721 # v2.10.2
        id: changes
        with:
          filters: |
            src:
            - '**.go'
            - '**/go.mod'
            - '**/go.sum'
            - '.golangci.yml'
  golangci:
    name: lint
    runs-on: ubuntu-latest
    needs: [changes]
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        if: github.event.schedule != '' || needs.changes.outputs.src == 'true'
        with:
          go-version-file: 'go.mod'
      - name: golangci-lint
        # any scheduled run or push/pulls with relevant changed paths, but skip PRs from release branches
        if: |
          github.event.schedule != '' ||
          (needs.changes.outputs.src == 'true' && (github.event_name == 'push' || github.event_name == 'pull_request'))
        ##
        # XXX: change this to the official action once multiple --out-format args are supported.
        # See: https://github.com/golangci/golangci-lint-action/issues/612
        ##
        uses: smartcontractkit/golangci-lint-action@54ab6c5f11d66a92d14c3f7cc41ea13f676644bd # feature/multiple-output-formats-backup
        with:
          version: v1.50.1
          allow-extra-out-format-args: true
          args: --out-format checkstyle:golangci-lint-report.xml
          only-new-issues: ${{github.event.schedule == ''}} # show only new issues, unless it's a scheduled run
          args: --out-format checkstyle:golangci-lint-report.xml
      - name: Store lint report artifact
        if: always()
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # v3.1.0
        with:
          name: golangci-lint-report
          path: golangci-lint-report.xml
      - name: Collect Metrics
        if: always()
        id: collect-gha-metrics
        uses: smartcontractkit/push-gha-metrics-action@808c183d1f5c26a4f3fd50b75d3cf7b58d9aa293
        with:
          basic-auth: ${{ secrets.GRAFANA_CLOUD_BASIC_AUTH }}
          hostname: ${{ secrets.GRAFANA_CLOUD_HOST }}
          this-job-name: lint
        continue-on-error: true
