name: Solidity Foundry
on: [pull_request]

env:
  FOUNDRY_PROFILE: ci
  # Has to match the `make foundry` version.
  FOUNDRY_VERSION: nightly-de33b6af53005037b463318d2628b5cfcaf39916
  # we run foundry on ubuntu-22.04, because of https://github.com/foundry-rs/foundry/issues/3827

jobs:
  changes:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      src_changes: ${{ steps.changes.outputs.src }}
      sol_changes: ${{ steps.changes.outputs.sol }}
      sol_files: ${{ steps.changes.outputs.sol_files }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          list-files: 'shell'
          filters: |
            src:
              - 'contracts/src/v0.8/**/*'
              - '.github/workflows/solidity-foundry.yml'
              - 'contracts/foundry.toml'
              - 'contracts/gas-snapshots/*.gas-snapshot'
            sol:
              - 'contracts/src/v0.8/**/*.sol'

  tests:
    if: needs.changes.outputs.src_changes == 'bum' # remove me
    strategy:
      fail-fast: false
      matrix:
        product:
          # 98.5 is the aspirational code coverage once we migrate all tests to Foundry
          # product that have that minimum coverage of 98.5 in the matrix below are currently excluded from the check
          - name: automation
            min-coverage: 98.5
          - name: functions
            min-coverage: 98.5
          - name: keystone
            min-coverage: 3.9
          - name: l2ep
            min-coverage: 3.67
          - name: llo-feeds
            min-coverage: 4.7
          - name: operatorforwarder
            min-coverage: 1.88
          - name: shared
            min-coverage: 1.9
          - name: vrf
            min-coverage: 98.5
    needs: [changes]
    name: Foundry Tests ${{ matrix.product.name }}
    runs-on: ubuntu-22.04

    # The if statements for steps after checkout repo is workaround for
    # passing required check for PRs that don't have filtered changes.
    steps:
      - name: Checkout the repo
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          submodules: recursive

      # Only needed because we use the NPM versions of packages
      # and not native Foundry. This is to make sure the dependencies
      # stay in sync.
      - name: Setup NodeJS
        if: needs.changes.outputs.src_changes == 'true'
        uses: ./.github/actions/setup-nodejs

      - name: Install Foundry
        if: needs.changes.outputs.src_changes == 'true'
        uses: foundry-rs/foundry-toolchain@8f1998e9878d786675189ef566a2e4bf24869773 # v1.2.0
        with:
          version: ${{ env.FOUNDRY_VERSION }}

      - name: Run Forge build
        if: needs.changes.outputs.src_changes == 'true'
        run: |
          forge --version
          forge build
        id: build
        working-directory: contracts
        env:
          FOUNDRY_PROFILE: ${{ matrix.product.name }}

      - name: Run Forge tests
        if: needs.changes.outputs.src_changes == 'true'
        run: |
          forge test -vvv
        id: test
        working-directory: contracts
        env:
          FOUNDRY_PROFILE: ${{ matrix.product.name }}

      - name: Run Forge snapshot
        if: ${{ !contains(fromJson('["vrf"]'), matrix.product.name) && !contains(fromJson('["automation"]'), matrix.product.name) && !contains(fromJson('["keystone"]'), matrix.product.name) && needs.changes.outputs.src_changes == 'true' }}
        run: |
          forge snapshot --nmt "testFuzz_\w{1,}?" --check gas-snapshots/${{ matrix.product.name }}.gas-snapshot
        id: snapshot
        working-directory: contracts
        env:
          FOUNDRY_PROFILE: ${{ matrix.product.name }}

      # required for code coverage report generation
      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@f5da1b26b0dcf5d893077a3c4f29cf78079c841d # v1.0.0

      - name: Run coverage
        if: ${{ !contains(fromJson('["vrf"]'), matrix.product.name) && !contains(fromJson('["automation"]'), matrix.product.name) && !contains(fromJson('["functions"]'), matrix.product.name) && needs.changes.outputs.src_changes == 'true' }}
        working-directory: contracts
        run: forge coverage --report lcov
        env:
          FOUNDRY_PROFILE: ${{ matrix.product.name }}

      # uncomment and adjust/create a script if we want to prune the report
      #      - name: Prune report
      #        if: ${{ needs.changes.outputs.changes == 'true' }}
      #        run: |
      #          sudo apt-get install lcov
      #          ./tools/ci/ccip_lcov_prune ./contracts/lcov.info ./lcov.info.pruned
      #        env:
      #          FOUNDRY_PROFILE: ${{ matrix.product }}

      - name: Report code coverage
        if: ${{ !contains(fromJson('["vrf"]'), matrix.product.name) && !contains(fromJson('["automation"]'), matrix.product.name) && !contains(fromJson('["functions"]'), matrix.product.name) && needs.changes.outputs.src_changes == 'true' }}
        uses: zgosalvez/github-actions-report-lcov@a546f89a65a0cdcd82a92ae8d65e74d450ff3fbc # v4.1.4
        with:
          update-comment: true
          coverage-files: ./contracts/lcov.info
          minimum-coverage: ${{ matrix.product.min-coverage }}
          artifact-name: code-coverage-report-${{ matrix.product.name }}
          working-directory: ./contracts
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Collect Metrics
        if: needs.changes.outputs.src_changes == 'true'
        id: collect-gha-metrics
        uses: smartcontractkit/push-gha-metrics-action@d9da21a2747016b3e13de58c7d4115a3d5c97935 # v3.0.1
        with:
          id: ${{ matrix.product }}-solidity-foundry
          org-id: ${{ secrets.GRAFANA_INTERNAL_TENANT_ID }}
          basic-auth: ${{ secrets.GRAFANA_INTERNAL_BASIC_AUTH }}
          hostname: ${{ secrets.GRAFANA_INTERNAL_HOST }}
          this-job-name: Foundry Tests ${{ matrix.product }}
        continue-on-error: true

  # we want to run formatting and static analysis only on modified contracts
#  find-modified-contracts:
#    needs: [ changes ]
#    name: Find modified contracts
#    runs-on: ubuntu-22.04
#    outputs:
#      contracts: ${{ env.CONTRACT_MATRIX }}
#    steps:
#      - name: Checkout the repo
#        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
#        with:
#          submodules: recursive
#          fetch-depth: 0
#
#      - name: Find modified contracts
#        shell: bash
#        run: |
#          git fetch origin ${{ github.base_ref }}
#          git diff --name-only --diff-filter=AMR origin/${{ github.base_ref }}...HEAD | \
#          grep -E '\.sol$' | \
#          sed 's|^contracts/||' | \
#          sort -u | \
#          awk -F'/' '{printf("{\"path\":\"%s\",\"product\":\"%s\"}\n", $0, $3)}' | \
#          jq -s '.' > modified_contracts.json
#          MATRIX=$(cat modified_contracts.json | jq -c .)
#          echo "CONTRACT_MATRIX=${MATRIX}" >> $GITHUB_ENV
#          echo "Found modified contracts:"
#          cat modified_contracts.json | jq .

  analyze:
    needs: [ changes ]
    name: Run static analysis
    if: needs.changes.outputs.sol_changes == 'true'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the repo
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          submodules: recursive

      - name: Setup NodeJS
        uses: ./.github/actions/setup-nodejs

      - name: Install semver
        shell: bash
        run: |
          npm install -g semver

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@8f1998e9878d786675189ef566a2e4bf24869773 # v1.2.0
        with:
          version: ${{ env.FOUNDRY_VERSION }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install solc-select and solc
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install solc-select
          sudo ln -s /usr/local/bin/solc-select /usr/bin/solc-select
          solc-select install 0.8.19
          solc-select use 0.8.19

      - name: Install Slither
        run: |
          python -m pip install --upgrade pip
          pip install slither-analyzer

      - name: Run Slither
        shell: bash
        run: |
          CHANGED="${{ needs.changes.outputs.sol_files }}"
          IFS=' ' read -r -a CHANGED_ARRAY <<< "$CHANGED"
          slither_errors=0
          for file in "${CHANGED_ARRAY[@]}"; do
            # Select the correct solc version for the file as it might differ between contracts leading to compilation errors                                
            source ./contracts/scripts/select_solc_version.sh "$file"
            exit_code=$?
            if [ $exit_code -ne 0 ]; then
              echo "Error: Failed to select the correct solc version for $file."
              slither_errors=$((slither_errors+1))
              continue
            fi
            
            slither --fail-none --checklist --markdown-root ${{ github.server_url }}/${{ github.repository }}/blob/${{ github.sha }}/ "$file" >> slither-results.md   
          done
          
          if [ $slither_errors -ne 0 ]; then
            echo
            echo "There were $slither_errors Slither execution errors NOT related to formatting. Some files weren't analyzed."
            exit 1
          else
            echo "All files passed static analysis check."
          fi
      - name: Print Slither summary
        shell: bash
        run: |
          echo "# Static analysis results " >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat slither-results.md >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Collect Metrics
        id: collect-gha-metrics
        uses: smartcontractkit/push-gha-metrics-action@dea9b546553cb4ca936607c2267a09c004e4ab3f # v3.0.0
        with:
          id: solidity-foundry-slither
          org-id: ${{ secrets.GRAFANA_INTERNAL_TENANT_ID }}
          basic-auth: ${{ secrets.GRAFANA_INTERNAL_BASIC_AUTH }}
          hostname: ${{ secrets.GRAFANA_INTERNAL_HOST }}
          this-job-name: Run static analysis
        continue-on-error: true

  fmt:
    needs: [ changes ]
    name: Check formatting
    if: needs.changes.outputs.sol_changes == 'bum' # change me to true
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the repo
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          submodules: recursive

      - name: Setup NodeJS
        uses: ./.github/actions/setup-nodejs

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@8f1998e9878d786675189ef566a2e4bf24869773 # v1.2.0
        with:
          version: ${{ env.FOUNDRY_VERSION }}

      - name: Run Forge fmt
        run: |
          FILE_LIST=$(echo "$SOL_FILES" | tr ' ' '\n')
          format_errors=0
          for file in $FILE_LIST; do
            sanitized_file="${file/contracts\//}"
            echo "Running forge fmt --check on $sanitized_file"
            forge fmt --check "$sanitized_file" || format_errors=$((format_errors+1))
          done
          if [ $format_errors -ne 0 ]; then
            echo "There were $format_errors formatting errors."
            exit 1
          else
            echo "All files are properly formatted."
          fi
        id: fmt
        working-directory: contracts

      - name: Collect Metrics
        id: collect-gha-metrics
        uses: smartcontractkit/push-gha-metrics-action@dea9b546553cb4ca936607c2267a09c004e4ab3f # v3.0.0
        with:
          id: solidity-foundry-fmt
          org-id: ${{ secrets.GRAFANA_INTERNAL_TENANT_ID }}
          basic-auth: ${{ secrets.GRAFANA_INTERNAL_BASIC_AUTH }}
          hostname: ${{ secrets.GRAFANA_INTERNAL_HOST }}
          this-job-name: Check formatting
        continue-on-error: true
