name: Solidity-Hardhat
on:
  pull_request:
    types: [labeled]
  workflow_dispatch:
    inputs:
      product:
        description: 'product for which to generate artifacts; should be the same as foundry profile'
        required: true
      base_ref:
        description: 'commit or tag to be used as base reference, when looking for modified Solidity files'
        required: true

env:
  FOUNDRY_PROFILE: ci
  # Has to match the `make foundry` version.
  FOUNDRY_VERSION: nightly-de33b6af53005037b463318d2628b5cfcaf39916
  # PRODUCT: ${{ github.event.inputs.product }}
  PRODUCT: "automation"

#TODO remove label trigger after testing

jobs:
  changes:
    name: Detect changes
    if: github.event.label.name == 'generate_review_artifact' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.changes.outputs.sol }}
      shared_changes: ${{ steps.changes.outputs.shared }}
      files: ${{ steps.changes.outputs.sol_files }}
    steps:
      - name: Check for commas or spaces in product input
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          product="${{ env.PRODUCT }}
          if [[ "$product" =~ [,\ ] ]]; then
            echo "Error: 'inputs.product' contains commas or spaces: \"${{ env.PRODUCT }}\". Please provide just a single valid product name."
            exit 1
          else
            echo "Product name is valid: $product"
          fi
      - name: Checkout the repo
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - name: Find modified contracts
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          list-files: 'csv'
          base: ${{ inputs.base_ref || github.base_ref }}
          filters: |
            sol:
              - 'contracts/src/v0.8/**/*.sol'
            shared:
              - 'contracts/src/v0.8/**/shared/**/*.sol'        

  # some of the artifacts can only be generated on product level, and we cannot scope them to single contracts
  # some product-level modifications might also require shared contracts changes, so if these happened we need to generate artifacts for shared contracts as well
  coverage-and-book:
    if: ${{ needs.changes.outputs.changes == 'true' }}
    name: Foundry Tests ${{ env.PRODUCT }}
    runs-on: ubuntu-22.04
    needs: [changes]
    steps:
      - name: Checkout the repo
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          submodules: recursive

      - name: Setup NodeJS
        uses: ./.github/actions/setup-nodejs

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@8f1998e9878d786675189ef566a2e4bf24869773 # v1.2.0
        with:
          version: ${{ env.FOUNDRY_VERSION }}

      - name: Run Forge build for ${{ env.PRODUCT }}
        run: |
          forge --version
          forge build
        working-directory: contracts
        env:
          FOUNDRY_PROFILE: ${{ env.PRODUCT }}

      - name: Run Forge build for shared contracts
        if: ${{ needs.changes.outputs.shared_changed == 'true' }}
        run: |
          forge --version
          forge build
        working-directory: contracts
        env:
          FOUNDRY_PROFILE: "shared"

      - name: Run coverage for ${{ env.PRODUCT }}
        if: ${{ !contains(fromJson('["vrf"]'), inputs.product) && !contains(fromJson('["automation"]'), inputs.product) && !contains(fromJson('["functions"]'), inputs.product) && needs.changes.outputs.changes == 'true' }}
        working-directory: contracts
        run: forge coverage --report lcov -report-file lcov-${{ env.PRODUCT }}.info
        env:
          FOUNDRY_PROFILE: ${{ env.PRODUCT }}

      - name: Run coverage for shared contracts
        if: ${{ needs.changes.outputs.shared_changed == 'true' }}
        working-directory: contracts
        run: forge coverage --report lcov --report-file lcov-shared.info
        env:
          FOUNDRY_PROFILE: "shared"

      # see what we should prune for other products
      #      - name: Prune report
      #        if: ${{ needs.changes.outputs.changes == 'true' }}
      #        run: |
      #          sudo apt-get install lcov
      #          ./tools/ci/ccip_lcov_prune ./contracts/lcov.info ./lcov.info.pruned
      #        env:
      #          FOUNDRY_PROFILE: ${{ matrix.product }}

      # We could gather coverage for all products

      - name: Report code coverage for ${{ env.PRODUCT }}
        if: ${{ !contains(fromJson('["vrf"]'), inputs.product) && !contains(fromJson('["automation"]'), inputs.name) && !contains(fromJson('["functions"]'), inputs.name) && needs.changes.outputs.changes == 'true' }}
        uses: zgosalvez/github-actions-report-lcov@a546f89a65a0cdcd82a92ae8d65e74d450ff3fbc # v4.1.4
        with:
          update-comment: true
          coverage-files: ./contracts/lcov-${{ env.PRODUCT }}.info
          minimum-coverage: 0
          artifact-name: code-coverage-report-${{ env.PRODUCT }}
          working-directory: ./contracts
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Report code coverage for shared contracts
        if: ${{ needs.changes.outputs.shared_changed == 'true' }}
        uses: zgosalvez/github-actions-report-lcov@a546f89a65a0cdcd82a92ae8d65e74d450ff3fbc # v4.1.4
        with:
          update-comment: true
          coverage-files: ./contracts/lcov-shared.info
          minimum-coverage: 0
          artifact-name: code-coverage-report-shared
          working-directory: ./contracts
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Forge doc for ${{ env.PRODUCT }}
        run: |
          forge doc --build -o docs/${{ env.PRODUCT }}
        working-directory: contracts
        env:
          FOUNDRY_PROFILE: ${{ env.PRODUCT }}

      - name: Run Forge doc for shared contracts
        if: ${{ needs.changes.outputs.shared_changed == 'true' }}
        run: |
          forge doc --build -o docs/shared
        working-directory: contracts
        env:
          FOUNDRY_PROFILE: "shared"

      - name: Upload Artifacts for ${{ env.PRODUCT }}
        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
        timeout-minutes: 2
        continue-on-error: true
        with:
          name: ${{ env.PRODUCT }}-artifacts
          path: |
            contracts/docs/${{ env.PRODUCT }}
            contracts/${{ env.PRODUCT }}-lcov.info
          retention-days: 7

      - name: Upload Artifacts for shared contracts
        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
        timeout-minutes: 2
        continue-on-error: true
        with:
          name: shared-artifacts
          path: |
            contracts/docs/shared
            contracts/shared-lcov.info
          retention-days: 7

  # Generates UML diagrams and Slither reports for modified contracts
  uml-static-analysis:
    if: ${{ needs.changes.outputs.changes == 'true' }}
    name: Generate UML and Slither reports for modified contracts
    runs-on: ubuntu-22.04
    needs: [changes]
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup NodeJS
        uses: ./.github/actions/setup-nodejs

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@8f1998e9878d786675189ef566a2e4bf24869773 # v1.2.0
        with:
          version: ${{ env.FOUNDRY_VERSION }}

      - name: Install Sol2uml
        run: |
          npm link sol2uml --only=production

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install solc-select and solc
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install solc-select
          sudo ln -s /usr/local/bin/solc-select /usr/bin/solc-select
          solc-select install 0.8.19
          solc-select use 0.8.19

      - name: Install Slither
        run: |
          python -m pip install --upgrade pip
          pip install slither-analyzer

      - name: Save basic info
        shell: bash
        run: |
          cd contracts
          
          echo "Commit SHA used to generate artifacts: ${{ github.sha }}" > commit_sha.txt
          contract_list="${{ needs.changes.outputs.files }}"
          new_line_list=$(echo "$contract_list" | tr ',' '\n' | sed 's/,$//')
          echo $new_line_list > modified_contracts.txt
          
          cat modified_contracts.txt

      - name: Generate UML
        shell: bash
        run: |
          contract_list="${{ needs.changes.outputs.files }}"
          ./contracts/scripts/generate_uml.sh "./" "contracts/uml" "$contract_list"

      - name: Generate Slither Markdown reports
        run: |
          contract_list="${{ needs.changes.outputs.files }}"
          
          cd contracts
          cleaned_list=$(echo "$comma_separated_list" | sed 's|contract/||g')
          
          echo "Processing contracts: $cleaned_list"
          ./scripts/generate_slither_report.sh "${{ github.server_url }}/${{ github.repository }}/blob/${{ github.sha }}/" .slither.config-artifacts.json "." "$cleaned_list" "slither-reports"

      - name: Upload UMLs and Slither reports
        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
        timeout-minutes: 10
        continue-on-error: true
        with:
          name: contracts-artifacts
          path: |
            contracts/uml
            contracts/slither-reports
            contracts/modified_contracts.txt
            contracts/commit_sha.txt
          retention-days: 7

  gather-all-artifacts:
    if: github.event.label.name == 'generate_review_artifact' || github.event_name == 'workflow_dispatch'
    name: Gather all artifacts
    runs-on: ubuntu-latest
    needs: [coverage-and-book, uml-static-analysis, changes]
    steps:
      - name: Download UMLs and Slither Reports artifact
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: contracts-artifacts
          path: review_artifacts/
      - name: Download ${{ env.PRODUCT }} artifacts
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: ${{ env.PRODUCT }}-artifacts
          path: review_artifacts/

      - name: Download shared artifacts
        if: ${{ needs.changes.outputs.shared_changed == 'true' }}
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: shared-artifacts
          path: review_artifacts/

      - name: Upload all artifacts as single package
        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
        with:
          name: review-artifacts
          path: review_artifacts/

      - name: Remove UML & Slither artifact
        uses: geekyeggo/delete-artifact@24928e75e6e6590170563b8ddae9fac674508aa1 # v5.0
        with:
          name: contracts-artifacts
      - name: Remove ${{ env.PRODUCT }} artifacts
        uses: geekyeggo/delete-artifact@24928e75e6e6590170563b8ddae9fac674508aa1 # v5.0
        with:
          name: ${{ env.PRODUCT }}-artifacts
      - name: Remove shared artifacts
        if: ${{ needs.changes.outputs.shared_changed == 'true' }}
        uses: geekyeggo/delete-artifact@24928e75e6e6590170563b8ddae9fac674508aa1 # v5.0
        with:
          name: shared-artifacts

      - name: Print Artifact URL
        run: |
          REPO_NAME="${GITHUB_REPOSITORY}"
          RUN_ID="${GITHUB_RUN_ID}"
          ARTIFACT_NAME="review-artifacts"
          ARTIFACT_URL="https://github.com/${REPO_NAME}/suites/${RUN_ID}/artifacts/${ARTIFACT_NAME}"
          echo "Artifact URL: ${ARTIFACT_URL}"
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_RUN_ID: ${{ github.run_id }}

      - name: Retrieve artifact ID
        id: get_artifact_id
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          ARTIFACTS=$(gh api -X GET repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts)
          ARTIFACT_ID=$(echo "$ARTIFACTS" | jq '.artifacts[] | select(.name=="review-artifacts") | .id')
          echo "Artifact ID: $ARTIFACT_ID"
          echo "artifact_id=$ARTIFACT_ID" >> $GITHUB_OUTPUT            

      # TODO remove ELSE branch after testing
      - name: Print Artifact URL in job summary
        run: |
          echo "#Solidity Review Artifact Generated" >> $GITHUB_STEP_SUMMARY
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "Base Ref used: ${{ inputs.base_ref }}" >> $GITHUB_STEP_SUMMARY
          else
            echo "Commit SHA used: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          fi
          echo "[Artifact URL](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.get_artifact_id.outputs.artifact_id }})" >> $GITHUB_STEP_SUMMARY        

      # TODO remove after testing
      - name: Print Artifact URL in PR comment
        uses: actions/github-script@v7
        if: github.event.label.name == 'generate_review_artifact'
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: `# Solidity Review Artifact Generated
            ## Commit SHA
            ${{ github.sha }}
            ## Artifact URL
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.get_artifact_id.outputs.artifact_id }}`
            });

  notify-no-changes:
    if: ${{ needs.changes.outputs.changes == 'false' }}
    needs: [changes]
    runs-on: ubuntu-latest
    steps:
      - name: Print warning in job summary
        shell: bash
        #TODO remove that and the else branch in shell after testing
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "#Solidity Review Artifact NOT Generated" >> $GITHUB_STEP_SUMMARY
             if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
               echo "Base Ref used: ${{ inputs.base_ref }}" >> $GITHUB_STEP_SUMMARY
               desc="No modified Solidity files found between ${{ inputs.base_ref }} and ${{ github.sha }} or they are located outside of './contracts' folder."
             else
               echo "Commit SHA used: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
               desc="No modified Solidity files found in the PR or they are located outside of './contracts' folder."
             fi
             echo "## Reason: No Solidity files found." >> $GITHUB_STEP_SUMMARY
             echo "$desc" >> $GITHUB_STEP_SUMMARY
          fi

#on:
#  merge_group:
#  push:
#
#env:
#  NODE_OPTIONS: --max_old_space_size=8192
#
#defaults:
#  run:
#    shell: bash
#
#jobs:
#  changes:
#    name: Detect changes
#    runs-on: ubuntu-latest
#    outputs:
#      changes: ${{ steps.changes.outputs.src }}
#    steps:
#      - name: Checkout the repo
#        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
#      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
#        id: changes
#        with:
#          filters: |
#            src:
#              - 'contracts/src/!(v0.8/(ccip|functions|keystone|l2ep|llo-feeds|transmission|vrf)/**)/**/*'
#              - 'contracts/test/**/*'
#              - 'contracts/package.json'
#              - 'contracts/pnpm-lock.yaml'
#              - 'contracts/hardhat.config.ts'
#              - '.github/workflows/solidity-hardhat.yml'
#
#  hardhat-test:
#    needs: [changes]
#    if: needs.changes.outputs.changes == 'true'
#    name: Solidity ${{ fromJSON('["(skipped)", ""]')[needs.changes.outputs.changes == 'true'] }}
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout the repo
#        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
#      - name: Setup NodeJS
#        uses: ./.github/actions/setup-nodejs
#      - name: Setup Hardhat
#        uses: ./.github/actions/setup-hardhat
#        with:
#          namespace: coverage
#      - name: Run tests
#        working-directory: contracts
#        run: pnpm test
#      - name: Collect Metrics
#        id: collect-gha-metrics
#        uses: smartcontractkit/push-gha-metrics-action@d9da21a2747016b3e13de58c7d4115a3d5c97935 # v3.0.1
#        with:
#          id: hardhat-test
#          org-id: ${{ secrets.GRAFANA_INTERNAL_TENANT_ID }}
#          basic-auth: ${{ secrets.GRAFANA_INTERNAL_BASIC_AUTH }}
#          hostname: ${{ secrets.GRAFANA_INTERNAL_HOST }}
#        continue-on-error: true
#
#  solidity:
#    needs: [changes, hardhat-test]
#    name: Solidity
#    runs-on: ubuntu-latest
#    if: always()
#    steps:
#      - run: echo 'Solidity tests finished!'
#      - name: Check test results
#        run: |
#          if [[ "${{ needs.changes.result }}" = "failure" || "${{ needs.solidity-splits.result }}" = "failure" ]]; then
#            echo "One or more changes / solidity-splits jobs failed"
#            exit 1
#          else
#            echo "All test jobs passed successfully"
#          fi
#      - name: Collect Metrics
#        if: always()
#        id: collect-gha-metrics
#        uses: smartcontractkit/push-gha-metrics-action@d9da21a2747016b3e13de58c7d4115a3d5c97935 # v3.0.1
#        with:
#          id: solidity-tests
#          org-id: ${{ secrets.GRAFANA_INTERNAL_TENANT_ID }}
#          basic-auth: ${{ secrets.GRAFANA_INTERNAL_BASIC_AUTH }}
#          hostname: ${{ secrets.GRAFANA_INTERNAL_HOST }}
#          this-job-name: Solidity
#        continue-on-error: true
